package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/HOLDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/zulu8-silver-build-win64/zulu-src/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Tuesday, January 12, 2021 7:48:17 AM PST
*/

public interface HOLDING
{

  /** Object adapter state that holds requests temporarily until the 
   * state is changed.
   */
  public static final short value = (short)(0);
}
