package org.omg.DynamicAny;


/**
* org/omg/DynamicAny/DynStruct.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/zulu8-silver-build-win64/zulu-src/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Tuesday, January 12, 2021 7:48:16 AM PST
*/


/**
    * DynStruct objects support the manipulation of IDL struct and exception values.
    * Members of the exceptions are handled in the same way as members of a struct.
    */
public interface DynStruct extends DynStructOperations, org.omg.DynamicAny.DynAny, org.omg.CORBA.portable.IDLEntity 
{
} // interface DynStruct
