package org.omg.PortableServer;


/**
* org/omg/PortableServer/IdAssignmentPolicy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/zulu8-silver-build-win64/zulu-src/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Tuesday, January 12, 2021 7:48:17 AM PST
*/


/**
	 * IdAssignmentPolicy specifies whether Object Ids in 
	 * the created POA are generated by the application or 
	 * by the ORB. The default is SYSTEM_ID.
	 */
public interface IdAssignmentPolicy extends IdAssignmentPolicyOperations, org.omg.CORBA.Policy, org.omg.CORBA.portable.IDLEntity 
{
} // interface IdAssignmentPolicy
